language: r
cran: https://cran.rstudio.com
cache: 
  packages: true

before_install:
  - nvm install stable
  - npm i netlify-cli -g
  - export COMMIT_MSG=$(echo "$TRAVIS_COMMIT_MESSAGE" | head -n1)
  - export DEPLOY_MSG="${TRAVIS_COMMIT:0:7} ${COMMIT_MSG:0:50}"
env:
  - NETLIFY_SITE_ID=82ff5a18-8a13-4f25-b688-230b04bc5664
  # NETLIFY_AUTH_TOKEN set in travis settings

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'
  - cp _redirects _book/_redirects # netlify redirects file

deploy:
  - provider: script
    script: netlify deploy --dir _book --prod --message "$DEPLOY_MSG"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: netlify deploy --dir _book --message "$DEPLOY_MSG"
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
